import {
  BookOpen,
  BrainCircuit,
  Calculator,
  Globe2,
  Languages,
  MonitorSmartphone,
  ScrollText,
} from "lucide-react";

export const boardExamDate = "2027-03-15T09:00:00+05:00";

export const subjects = [
  {
    slug: "physics",
    name: "Physics",
    short: "Phy",
    color: "from-sky-500/30 via-cyan-400/18 to-transparent",
    accent: "bg-sky-400",
    text: "text-sky-200",
    icon: BrainCircuit,
    completion: 74,
    completedChapters: 11,
    totalChapters: 15,
    remainingHours: 21,
    rank: 2,
    friendsAhead: ["Bilal"],
    chapters: [
      ["Motion & Force", 100, 12, 3, true],
      ["Work, Power & Energy", 88, 10, 2, true],
      ["Waves & Sound", 70, 8, 2, false],
      ["Electrostatics", 58, 7, 1, false],
      ["Current Electricity", 42, 6, 1, false],
    ],
  },
  {
    slug: "computer",
    name: "Computer",
    short: "CS",
    color: "from-cyan-500/30 via-blue-400/18 to-transparent",
    accent: "bg-cyan-400",
    text: "text-cyan-200",
    icon: MonitorSmartphone,
    completion: 82,
    completedChapters: 9,
    totalChapters: 11,
    remainingHours: 12,
    rank: 1,
    friendsAhead: [],
    chapters: [
      ["Introduction to Computing", 100, 5, 2, true],
      ["Programming Fundamentals", 94, 16, 4, true],
      ["Data Structures", 78, 12, 2, false],
      ["Databases", 65, 7, 1, false],
      ["Networking Basics", 55, 6, 1, false],
    ],
  },
  {
    slug: "math",
    name: "Math",
    short: "Math",
    color: "from-violet-500/28 via-fuchsia-400/16 to-transparent",
    accent: "bg-violet-400",
    text: "text-violet-200",
    icon: Calculator,
    completion: 68,
    completedChapters: 10,
    totalChapters: 16,
    remainingHours: 28,
    rank: 3,
    friendsAhead: ["Ali", "Bilal"],
    chapters: [
      ["Functions & Limits", 100, 13, 3, true],
      ["Differentiation", 76, 11, 2, false],
      ["Integration", 52, 8, 1, false],
      ["Conic Sections", 61, 9, 2, false],
      ["Vectors", 48, 6, 1, false],
    ],
  },
  {
    slug: "english",
    name: "English",
    short: "Eng",
    color: "from-amber-500/25 via-orange-400/18 to-transparent",
    accent: "bg-amber-400",
    text: "text-amber-200",
    icon: Languages,
    completion: 79,
    completedChapters: 8,
    totalChapters: 10,
    remainingHours: 9,
    rank: 2,
    friendsAhead: ["Musa"],
    chapters: [
      ["Comprehension", 100, 6, 3, true],
      ["Grammar & Tenses", 91, 9, 4, true],
      ["Essay Writing", 68, 7, 2, false],
      ["Translation Practice", 59, 6, 1, false],
    ],
  },
  {
    slug: "urdu",
    name: "Urdu",
    short: "Urdu",
    color: "from-emerald-500/25 via-green-400/15 to-transparent",
    accent: "bg-emerald-400",
    text: "text-emerald-200",
    icon: ScrollText,
    completion: 73,
    completedChapters: 7,
    totalChapters: 10,
    remainingHours: 10,
    rank: 4,
    friendsAhead: ["Hamza", "Bilal", "Ali"],
    chapters: [
      ["Nazam Revision", 88, 6, 3, true],
      ["Ghazal Analysis", 72, 7, 2, false],
      ["Grammar", 76, 5, 2, false],
      ["Translation", 57, 4, 1, false],
    ],
  },
  {
    slug: "tarjuma-tul-quran",
    name: "Tarjuma-Tul-Quran",
    short: "TTQ",
    color: "from-teal-500/25 via-emerald-400/16 to-transparent",
    accent: "bg-teal-400",
    text: "text-teal-200",
    icon: BookOpen,
    completion: 77,
    completedChapters: 6,
    totalChapters: 8,
    remainingHours: 8,
    rank: 1,
    friendsAhead: [],
    chapters: [
      ["Surah Themes", 100, 5, 2, true],
      ["Word-to-word Translation", 83, 6, 2, true],
      ["Context & Explanation", 71, 5, 1, false],
      ["MCQ Drills", 62, 4, 1, false],
    ],
  },
  {
    slug: "pak-studies",
    name: "Pak Studies",
    short: "Pak",
    color: "from-rose-500/28 via-orange-400/16 to-transparent",
    accent: "bg-rose-400",
    text: "text-rose-200",
    icon: Globe2,
    completion: 71,
    completedChapters: 7,
    totalChapters: 11,
    remainingHours: 14,
    rank: 3,
    friendsAhead: ["Musa", "Bilal"],
    chapters: [
      ["Ideology of Pakistan", 93, 7, 3, true],
      ["Constitutional Development", 64, 6, 2, false],
      ["Geography", 58, 5, 1, false],
      ["Foreign Relations", 52, 4, 1, false],
    ],
  },
] as const;

export const friends = [
  {
    id: "bilal",
    name: "Bilal",
    username: "@bilal",
    avatar: "BI",
    xp: 19310,
    streak: 31,
    progress: 81,
    todayMinutes: 281,
    rank: 1,
    movement: "up",
    level: 20,
    online: true,
    glow: "from-amber-300 to-yellow-500",
    bio: "Current throne holder. Turns mock tests into personal announcements.",
  },
  {
    id: "ahmed",
    name: "Ahmed",
    username: "@ahmed",
    avatar: "AH",
    xp: 18240,
    streak: 26,
    progress: 75,
    todayMinutes: 234,
    rank: 2,
    movement: "up",
    level: 19,
    online: true,
    glow: "from-cyan-400 to-sky-500",
    bio: "Silent grinder. Physics hunter. Loves stealing rank with late-night revisions.",
  },
  {
    id: "ali",
    name: "Ali",
    username: "@ali",
    avatar: "AL",
    xp: 17690,
    streak: 17,
    progress: 72,
    todayMinutes: 210,
    rank: 3,
    movement: "down",
    level: 18,
    online: true,
    glow: "from-slate-200 to-slate-400",
    bio: "Math specialist. Dangerous on weekends.",
  },
  {
    id: "hassan",
    name: "Hassan",
    username: "@hassan",
    avatar: "HS",
    xp: 16020,
    streak: 14,
    progress: 68,
    todayMinutes: 174,
    rank: 4,
    movement: "same",
    level: 16,
    online: false,
    glow: "from-orange-300 to-amber-500",
    bio: "Long-session machine. Starts quiet, ends with surprise jumps.",
  },
  {
    id: "hamza",
    name: "Hamza",
    username: "@hamza",
    avatar: "HZ",
    xp: 15100,
    streak: 12,
    progress: 65,
    todayMinutes: 149,
    rank: 5,
    movement: "up",
    level: 15,
    online: true,
    glow: "from-emerald-300 to-teal-500",
    bio: "Urdu and TTQ comeback artist.",
  },
  {
    id: "musa",
    name: "Musa",
    username: "@musa",
    avatar: "MU",
    xp: 14740,
    streak: 22,
    progress: 64,
    todayMinutes: 168,
    rank: 6,
    movement: "down",
    level: 15,
    online: false,
    glow: "from-violet-300 to-fuchsia-500",
    bio: "Essay king with dangerous end-game energy.",
  },
  {
    id: "zain",
    name: "Zain",
    username: "@zain",
    avatar: "ZN",
    xp: 13890,
    streak: 8,
    progress: 59,
    todayMinutes: 118,
    rank: 7,
    movement: "same",
    level: 14,
    online: true,
    glow: "from-sky-300 to-indigo-500",
    bio: "Fast bursts, fast climbs.",
  },
  {
    id: "areeb",
    name: "Areeb",
    username: "@areeb",
    avatar: "AR",
    xp: 12930,
    streak: 4,
    progress: 53,
    todayMinutes: 91,
    rank: 8,
    movement: "down",
    level: 12,
    online: false,
    glow: "from-rose-300 to-pink-500",
    bio: "Needs one good streak to scare everybody.",
  },
] as const;

export const currentUser = friends.find((friend) => friend.id === "ahmed")!;

export const activities = [
  {
    id: 1,
    friend: "Ahmed",
    avatar: "AH",
    action: "completed Physics Chapter 5",
    time: "2m ago",
    type: "chapter",
  },
  {
    id: 2,
    friend: "Ali",
    avatar: "AL",
    action: "reached 70% Math syllabus",
    time: "6m ago",
    type: "milestone",
  },
  {
    id: 3,
    friend: "Hassan",
    avatar: "HS",
    action: "started a 3-hour study sprint",
    time: "11m ago",
    type: "session",
  },
  {
    id: 4,
    friend: "Bilal",
    avatar: "BI",
    action: "defended Rank #1 with 420 XP",
    time: "14m ago",
    type: "rank",
  },
  {
    id: 5,
    friend: "Hamza",
    avatar: "HZ",
    action: "hit a 12-day streak milestone",
    time: "18m ago",
    type: "streak",
  },
  {
    id: 6,
    friend: "Musa",
    avatar: "MU",
    action: "finished English essay revision",
    time: "24m ago",
    type: "chapter",
  },
  {
    id: 7,
    friend: "Areeb",
    avatar: "AR",
    action: "lost streak after missing yesterday's targets",
    time: "31m ago",
    type: "danger",
  },
  {
    id: 8,
    friend: "Zain",
    avatar: "ZN",
    action: "jumped past Musa in daily study time",
    time: "44m ago",
    type: "rank",
  },
] as const;

export const dailyTasks = [
  {
    id: "task-1",
    title: "Physics Chapter 5 numericals",
    xp: 150,
    eta: "55 min",
    completed: true,
    tag: "Deep Work",
  },
  {
    id: "task-2",
    title: "2-hour focused study block",
    xp: 200,
    eta: "2h",
    completed: true,
    tag: "Session",
  },
  {
    id: "task-3",
    title: "English grammar revision set",
    xp: 90,
    eta: "35 min",
    completed: false,
    tag: "Revision",
  },
  {
    id: "task-4",
    title: "Math integration practice",
    xp: 170,
    eta: "1h 10m",
    completed: false,
    tag: "Problem Solving",
  },
  {
    id: "task-5",
    title: "TTQ word meanings recap",
    xp: 80,
    eta: "25 min",
    completed: false,
    tag: "Memory",
  },
] as const;

export const heatmap = [
  2, 4, 3, 0, 5, 4, 1, 3, 4, 5, 2, 1, 0, 3, 4, 5, 5, 2, 1, 4, 4, 3, 2, 5, 1, 0, 4, 5,
];

export const rankHistory = [
  { label: "W1", rank: 6 },
  { label: "W2", rank: 5 },
  { label: "W3", rank: 4 },
  { label: "W4", rank: 4 },
  { label: "W5", rank: 3 },
  { label: "W6", rank: 2 },
];

export const achievementBadges = [
  "Night Sprint",
  "3-Day Crush",
  "Physics Hunter",
  "Comeback Kid",
  "Consistency Beast",
];
